[pytest]
addopts = -v -s --alluredir=allure-results --clean-alluredir -W ignore::urllib3.exceptions.InsecureRequestWarning
testpaths = run_agents.py tests/test_agent_results.py tests/test_api_results.py tests/test_bugs.py tests/test_generated_tcs.py tests/test_user_stories.py
python_files = run_agents.py test_*.py tests/test_*.py
python_functions = test_*
console_output_style = progress
