# tests/test_user_stories.py
#
# FIX: Stories now load at EXECUTION TIME not collection time.
# This means stories generated by the agent in the SAME run
# are picked up and executed — previously they were missed because
# collection happens before the agent runs and saves story files.
#
# How it works:
# - pytest_generate_tests uses a sentinel ["__load_at_runtime__"]
# - test_user_story loads the actual stories when it executes
# - Each story becomes its own Allure step (not a separate test)
# - STORY_ENABLED=false → generates zero tests (clean dashboard)

import pytest
import allure
import os
from playwright.sync_api import Page
from config import CFG


def _story_enabled() -> bool:
    return os.environ.get("STORY_ENABLED", "false").lower() in ("1", "true", "yes")


def _get_run_id() -> str:
    try:
        from run_context import RUN_ID
        return RUN_ID
    except Exception:
        return None


def pytest_generate_tests(metafunc):
    if "story_sentinel" not in metafunc.fixturenames:
        return
    if not _story_enabled():
        # Zero tests — nothing appears on dashboard when disabled
        metafunc.parametrize("story_sentinel", [], ids=[])
        return
    # Single test that loads all stories at runtime
    metafunc.parametrize("story_sentinel", ["__run__"], ids=["auto-stories"])


@allure.feature("🔄 Regression Stories")
def test_user_story(page: Page, story_sentinel):
    """
    Loads and runs all auto-generated stories from this run.
    Each story is a flat Allure step — no deep nesting.
    PASS = all stories passed. FAIL = at least one story failed.
    """
    if not _story_enabled():
        pytest.skip("STORY_ENABLED=false")

    run_id = _get_run_id()

    # Load at EXECUTION time — catches stories generated this same run
    from agents.story_runner import load_auto_stories, run_story
    stories = load_auto_stories(run_id)

    if not stories:
        allure.dynamic.title("⏭ No Auto Stories Generated This Run")
        allure.dynamic.severity(allure.severity_level.NORMAL)
        allure.dynamic.description(
            "No auto-generated stories found for this run.\n\n"
            "Stories are generated when STORY_ENABLED=true and the agent "
            "discovers test cases during exploration.\n\n"
            f"Run ID: {run_id}"
        )
        return  # PASS

    allure.dynamic.title(
        f"🔄 {len(stories)} Auto Regression Story(ies) — Run {run_id}")
    allure.dynamic.severity(allure.severity_level.NORMAL)
    allure.dynamic.description(
        f"**Run ID:** {run_id}  \n"
        f"**Stories:** {len(stories)}  \n\n" +
        "\n".join(
            f"- {s.get('name','Unnamed')} ({s.get('priority','medium')} priority)"
            for s in stories
        )
    )
    allure.dynamic.tag("auto-generated")
    allure.dynamic.tag(f"run:{run_id}")
    allure.dynamic.tag(f"stories:{len(stories)}")

    failures = []

    for i, story in enumerate(stories, 1):
        name     = story.get("name", f"Story {i}")
        priority = story.get("priority", "medium")
        site     = story.get("_site", "")
        steps    = story.get("steps", [])

        sev_icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(
            priority.lower(), "⚪")

        with allure.step(f"{sev_icon} Story {i}/{len(stories)}: {name}"):
            allure.attach(
                f"Name     : {name}\n"
                f"Priority : {priority}\n"
                f"Site     : {site}\n"
                f"Steps    : {len(steps)}\n"
                f"Desc     : {story.get('description', '')}\n"
                f"Source   : {story.get('_file', 'auto-generated')}",
                name="Story Details",
                attachment_type=allure.attachment_type.TEXT,
            )

            result = run_story(page, story, agent_id="story-runner")

            allure.attach(
                result.summary(),
                name=f"{'✅ PASS' if result.status == 'PASS' else '❌ FAIL'} — Story Result",
                attachment_type=allure.attachment_type.TEXT,
            )

            if result.status == "FAIL":
                failures.append({"story": name, "failures": result.failures})
                allure.attach(
                    f"Story '{name}' FAILED:\n" +
                    "\n".join(
                        f"  ❌ {f['step']}: {f['error'][:100]}"
                        for f in result.failures
                    ),
                    name="❌ Failure Details",
                    attachment_type=allure.attachment_type.TEXT,
                )

    if failures:
        pytest.fail(
            f"{len(failures)} of {len(stories)} story(ies) failed:\n" +
            "\n".join(
                f"  '{f['story']}': " +
                ", ".join(x["error"][:60] for x in f["failures"])
                for f in failures
            )
        )
