# agents/story_runner.py
#
# PHASE 4: Execute auto-generated stories as regression tests.
# Uses Playwright directly — no MCP server needed.

import allure
import os
import re
import time
import yaml
from playwright.sync_api import Page, TimeoutError as PWTimeout
from browser.screenshot import capture_step_screenshot
from browser.login_handler import attempt_login
from brain.action_executor import execute_action


class StoryResult:
    def __init__(self, name: str, url: str):
        self.name          = name
        self.url           = url
        self.steps_total   = 0
        self.steps_passed  = 0
        self.steps_failed  = 0
        self.failures      = []
        self.duration      = 0.0
        self.status        = "PASS"

    def add_step(self, name: str, passed: bool, error: str = ""):
        self.steps_total += 1
        if passed:
            self.steps_passed += 1
        else:
            self.steps_failed += 1
            self.failures.append({"step": name, "error": error})
            self.status = "FAIL"

    def summary(self) -> str:
        icon  = "✅" if self.status == "PASS" else "❌"
        lines = [
            f"Story:   {self.name}",
            f"Status:  {icon} {self.status}",
            f"Steps:   {self.steps_passed}/{self.steps_total} passed",
            f"Time:    {self.duration:.1f}s",
        ]
        if self.failures:
            lines.append("Failures:")
            for f in self.failures:
                lines.append(f"  ❌ {f['step']}: {f['error'][:80]}")
        return "\n".join(lines)


def load_auto_stories(run_id: str = None) -> list:
    """Load auto-generated stories from stories/auto/ directory."""
    auto_dir = os.path.join("stories", "auto")
    if not os.path.isdir(auto_dir):
        return []

    stories = []
    files   = sorted(os.listdir(auto_dir), reverse=True)  # newest first

    for fname in files:
        if not fname.endswith((".yaml", ".yml")):
            continue
        # If run_id given, only load stories from that run
        if run_id and run_id not in fname:
            continue
        fpath = os.path.join(auto_dir, fname)
        try:
            with open(fpath, encoding="utf-8") as f:
                data = yaml.safe_load(f)
            if data and "stories" in data:
                site  = data.get("site", "")
                for s in data["stories"]:
                    s["_site"]  = site
                    s["_file"]  = fname
                    s["_auto"]  = True
                    stories.append(s)
                print(f"[STORY] Loaded {len(data['stories'])} auto-stories from {fname}")
        except Exception as e:
            print(f"[STORY] Could not load {fpath}: {e}")

    return stories


def run_story(page: Page, story: dict, agent_id: str = "") -> StoryResult:
    """Execute one story. Returns StoryResult."""
    name  = story.get("name", "Unnamed Story")
    site  = story.get("_site", "")
    steps = story.get("steps", [])

    result = StoryResult(name, site)
    start  = time.time()
    auto   = story.get("_auto", False)
    label  = "🤖 Auto" if auto else "📖 Manual"

    print(f"\n[STORY] {label}: '{name}' ({len(steps)} steps)")

    with allure.step(f"{label} Story: {name}"):
        allure.attach(
            f"Story:    {name}\n"
            f"Site:     {site}\n"
            f"Priority: {story.get('priority','medium')}\n"
            f"Source:   {'Auto-generated by Ollama' if auto else 'Manual YAML'}\n"
            f"Steps:    {len(steps)}\n"
            f"Desc:     {story.get('description','')}",
            name="Story Details",
            attachment_type=allure.attachment_type.TEXT,
        )

        for i, step in enumerate(steps, 1):
            action    = step.get("action", "unknown")
            desc      = step.get("description", step.get("message", ""))
            step_name = f"Step {i}: {action}" + (f" — {desc}" if desc else "")

            with allure.step(step_name):
                passed, error = _execute_step(page, step)
                result.add_step(step_name, passed, error)

                if passed:
                    allure.attach(f"✅ {step_name}", name="Result",
                                  attachment_type=allure.attachment_type.TEXT)
                else:
                    allure.attach(
                        f"❌ FAILED: {step_name}\nError: {error}",
                        name="Step Failed",
                        attachment_type=allure.attachment_type.TEXT,
                    )
                    ss = capture_step_screenshot(page, f"story_fail_step{i}")
                    if ss and os.path.exists(ss):
                        with open(ss, "rb") as f:
                            allure.attach(f.read(), name="Failure Screenshot",
                                          attachment_type=allure.attachment_type.PNG)
                    if step.get("stop_on_fail", True):
                        break

    result.duration = time.time() - start
    icon = "✅" if result.status == "PASS" else "❌"
    print(f"[STORY] {icon} '{name}': "
          f"{result.steps_passed}/{result.steps_total} steps, "
          f"{result.duration:.1f}s")
    allure.attach(result.summary(), name="Story Result",
                  attachment_type=allure.attachment_type.TEXT)
    return result


def _execute_step(page: Page, step: dict) -> tuple:
    """Execute one step. Returns (passed, error)."""
    action  = step.get("action", "")
    timeout = step.get("timeout", 10000)

    try:
        if action == "navigate":
            page.goto(step.get("url",""), wait_until="domcontentloaded",
                      timeout=60000)
            return True, ""

        elif action == "login":
            result = attempt_login(page, step.get("username",""),
                                   step.get("password",""))
            return (True, "") if result.get("success") else \
                   (False, f"Login failed: {result.get('error','unknown')}")

        elif action == "fill":
            field = step.get("field", "")
            value = step.get("value", "")
            for sel in [
                f"input[placeholder*='{field}' i]",
                f"input[name*='{field}' i]",
                f"input[id*='{field}' i]",
                f"input[aria-label*='{field}' i]",
            ]:
                try:
                    if page.locator(sel).count() > 0:
                        page.locator(sel).first.fill(value)
                        return True, ""
                except Exception:
                    continue
            try:
                page.get_by_label(field, exact=False).first.fill(value)
                return True, ""
            except Exception:
                pass
            return False, f"Field not found: '{field}'"

        elif action == "click":
            text = step.get("text", "")
            r1   = execute_action(page, f"click_link:{text}")
            if "no " not in r1.lower() and "error" not in r1.lower():
                return True, ""
            r2 = execute_action(page, f"click_button:{text}")
            if "no " not in r2.lower() and "error" not in r2.lower():
                return True, ""
            return False, f"Could not click: '{text}'"

        elif action == "assert_text_present":
            text = step.get("text", "")
            msg  = step.get("message", f"Text not found: '{text}'")
            try:
                page.wait_for_selector(f"text={text}", timeout=timeout)
                return True, ""
            except PWTimeout:
                try:
                    if text.lower() in page.content().lower():
                        return True, ""
                except Exception:
                    pass
                return False, msg

        elif action == "assert_url_contains":
            value = step.get("value", "")
            msg   = step.get("message", f"URL should contain '{value}'")
            page.wait_for_timeout(1000)
            if value.lower() in page.url.lower():
                return True, ""
            return False, f"{msg} — got: {page.url}"

        elif action == "assert_element":
            sel = step.get("selector", "")
            msg = step.get("message", f"Element not found: '{sel}'")
            try:
                page.wait_for_selector(sel, timeout=timeout)
                return True, ""
            except PWTimeout:
                return False, msg

        elif action == "wait":
            page.wait_for_timeout(step.get("ms", 1000))
            return True, ""

        elif action == "screenshot":
            ss = capture_step_screenshot(page, step.get("label","story_ss"))
            if ss and os.path.exists(ss):
                with open(ss,"rb") as f:
                    allure.attach(f.read(), name="Screenshot",
                                  attachment_type=allure.attachment_type.PNG)
            return True, ""

        elif action == "scroll":
            page.evaluate(f"window.scrollBy(0, {step.get('amount', 400)})")
            return True, ""

        else:
            return False, f"Unknown action: '{action}'"

    except Exception as e:
        return False, str(e)[:150]
